### ISSUE TITLE
[BUG] executing "mailu/templates/mysql.yaml" at <eq .Values.database.type "mysql">: error calling eq: invalid type for comparison

### ISSUE THREAD

**Issue by MSandro** [Mailu/helm-charts#109]
**Describe the bug**
Can not deploy Mailu with the Helm Chart.

**Environment**
 - Kubernetes Platform: Rancher2

**Additional context**
Values.yaml:
```
domain: mail.mydomain.com
hostnames:
- mail..mydomain.com
initialAccount:
  domain: mail..mydomain.com
  password: chang3m3!
  username: mailadmin
logLevel: INFO
mail:
  authRatelimit: 100/minute;3600/hour
  messageSizeLimitInMegabytes: 200
persistence:
  size: 100Gi
  existingClaim: mailu
secretKey: chang3m3!
```

Output:
```
helm install --namespace=mail --timeout=10m0s --values=/home/shell/helm/values-mailu-0.1.2.yaml --version=0.1.2 --wait=true mailu /home/shell/helm/mailu-0.1.2.tgz
Wed, Sep 29 2021 8:34:53 am | Error: template: mailu/templates/mysql.yaml:1:15: executing "mailu/templates/mysql.yaml" at <eq .Values.database.type "mysql">: error calling eq: invalid type for comparison
```
