### ISSUE TITLE
[BUG] Replying to a message causes rspamd crash (RPi/ARM)

### ISSUE THREAD

**Issue by technodrome** [Mailu/helm-charts#113]
### Environment
Mailu 1.8 (Helm), using images from `leolivier/mailu_*`, running on RPi cluster, three nodes (4 GB memory each), NFS share as shared data storage, OS Raspbian GNU/Linux 10 (buster), kernel 5.10.63-v8+, K3s version: v1.21.0+k3s1, containerd://1.4.4-k3s1

`my-values-file.yaml`
```yaml
# A list of mail hostnames is required. The first will be used as primary mail hostname
hostnames:
 - mail.macgyver.com # fake hostname

# The mail domain is required. See https://github.com/leolivier/mailu_leolivier/mailu_blob/master/docs/faq.rst#what-is-the-difference-between-domain-and-hostnames
domain: macgyver.com

# The secret key is required for protecting authentication cookies and must be set individually for each deployment
secretKey: XXXXXXXX

# An initial account can automatically be created:
initialAccount:
 username: mailadmin
 domain: macgyver.com
 password: xxxxxxx

nameOverride: ""
fullnameOverride: ""
clusterDomain: cluster.local

nodeSelector: {}

# Tolerations for pod assignment
# Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: {}

# Affinity for pod assignment
# Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}

database:
  # type of the database for mailu (sqlite or mysql)
  # default database is an embedded sqlite
  # for mysql, see settings below
  type: sqlite

  # type of the database for roundcube (sqlite or mysql)
  # default database is an embedded sqlite
  # for mysql, see settings below
  roundcubeType: sqlite

# For mysql/mariadb use the following config:
# Set the host to use an external database.
# If not host is set, a database instance is created by this chart.
#   type: mysql
  mysql: {}
    # host: external-db-hostname
    # root password for mysql database
    # rootPassword: chang3m3! # can only be set for embedded mysql

    # settings for mailu (required if mailu database type is "mysql")
    # database: mailu
    # user: mailu
    # password: chang3m3!

  # For an external PostgreSQL database, use the following config:
  postgresql: {}
    # host: external-db-hostname
    # database: mailu
    # user: mailu
    # password: chang3m3!

    # settings for roundcube (required if roundcube database type is "mysql" or "postgresql")
    # roundcubeDatabase: roundcube
    # roundcubeUser: roundcube
    # roundcubePassword: chang3m3!

external_relay: {}
#    host: "[domain.tld]:port"
#    username: username
#    password: SECRET

persistence:
  size: 100Gi
  accessMode: ReadWriteOnce
  #annotations:
  #  "helm.sh/resource-policy": keep
  #hostPath: /path/on/the/host
  #existingClaim: name-of-existing.claim
  storageClass: nfs-client
  #claimNameOverride: my-claim-name

# Change this if you're using different address ranges for pods
subnet: 10.42.0.0/16

# Version of mailu docker images to use when not specified otherwise
mailuVersion: 1.8

# default log level. can be overridden globally or per service
logLevel: WARNING

mail:
  messageSizeLimitInMegabytes: 50
  authRatelimit: 10/minute;1000/hour

# certmanager settings
certmanager:
  enabled: true
  issuerType: ClusterIssuer
  issuerName: letsencrypt-production
  apiVersion: cert-manager.io/v1

# Set ingress and loadbalancer config
ingress:
  externalIngress: true
  tlsFlavor: cert
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"

# Frontend load balancer for non-HTTP(s) services
front:
  # logLevel: WARNING
  image:
    repository: leolivier/mailu_nginx
    # tag defaults to mailuVersion
    tag: rpi-armv7-1.8-release
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 200m
  # Deployment or DaemonSet
  controller:
    kind: Deployment

admin:
  # logLevel: WARNING
  image:
    repository: leolivier/mailu_admin
    # tag defaults to mailuVersion
    tag: rpi-armv7-1.8-release
  resources:
    requests:
      memory: 500Mi
      cpu: 500m
    limits:
      memory: 500Mi
      cpu: 500m
  podAnnotations: {}

redis:
  image:
    repository: redis
    tag: 5-alpine
  resources:
    requests:
      memory: 200Mi
      cpu: 100m
    limits:
      memory: 300Mi
      cpu: 200m

postfix:
  # logLevel: WARNING
  image:
    repository: leolivier/mailu_postfix
    # tag defaults to mailuVersion
    tag: rpi-armv7-1.8-release
  resources:
    requests:
      memory: 2Gi
      cpu: 500m
    limits:
      memory: 2Gi
      cpu: 500m

dovecot:
  enabled: true
  # logLevel: WARNING
  image:
    repository: leolivier/mailu_dovecot
    # tag defaults to mailuVersion
    tag: rpi-armv7-1.8-release
  resources:
    requests:
      memory: 500Mi
      cpu: 500m
    limits:
      memory: 500Mi
      cpu: 500m
  # enable dovecot overrides
  # overrides:
  #   dovecot.conf: |
  #     # More info here: https://mailu.io/1.8/kubernetes/leolivier/mailu_index.html#dovecot
  #     mail_nfs_index = yes
  #     mail_nfs_storage = yes
  #     mail_fsync = always
  #     mmap_disable = yes
  #     mail_max_userip_connections=100

rspamd:
  # logLevel: WARNING
  image:
    repository: leolivier/mailu_rspamd
    # tag defaults to mailuVersion
    tag: rpi-armv7-1.8-release
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 200m

clamav:
  enabled: false
  # logLevel: WARNING
  image:
    repository: leolivier/mailu_clamav
    # tag defaults to mailuVersion
    tag: rpi-armv7-1.8-release
  resources:
    requests:
      memory: 1Gi
      cpu: 1000m
    limits:
      memory: 2Gi
      cpu: 1000m

roundcube:
  enabled: true
  # logLevel: WARNING
  image:
    repository: leolivier/mailu_roundcube
    # tag defaults to mailuVersion
    tag: rpi-armv7-1.8-release
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 200m


webdav:
  enabled: true
  # logLevel: WARNING
  image:
    repository: leolivier/mailu_radicale
    # tag defaults to mailuVersion
    tag: rpi-armv7-1.8-release

mysql:
  image:
    repository: library/mariadb
    tag: 10.4.10
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m

fetchmail:
  enabled: true
  # logLevel: WARNING
  image:
    repository: leolivier/mailu_fetchmail
    # tag defaults to mailuVersion
    tag: rpi-armv7-1.8-release
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 200m
  delay: 600
```

## Description
With the abovementioned .yaml values file and clamav disabled and "enable spam filter" disabled for the current user, **replying** to a message fails with the following error (user names, domains and IP addresses redacted):

```
Oct 21 13:15:22 mail postfix/smtpd[12073]: connect from 10-42-0-58.mailu-front.mailu-mailserver.svc.cluster.local[10.42.0.58]
Oct 21 13:15:23 mail postfix/smtpd[12073]: 181C8A00079: client=unknown[000.000.000.000], sasl_method=XCLIENT, sasl_username=mac@macgyver.com
Oct 21 13:15:23 mail postfix/cleanup[12076]: 181C8A00079: replace: header Received: from [127.0.0.1] (unknown [000.000.000.000])??by mail.macgyver.com (Postfix) with ESMTPA id 181C8A00079??for <XXX@gmail.com>; Thu, 21 Oct 2021 13:15:22 +0000 (UTC) from unknown[000.000.000.000]; from=<mac@macgyver.com> to=<XXX@gmail.com> proto=ESMTP helo=<[127.0.0.1]>: Received: from authenticated-user (mail.macgyver.com [111.111.111.111])??by mail.macgyver.com (Postfix) with ESMTPA id 181C8A00079??for <XXX@gmail.com>; Thu, 21 Oct 2021 13:15:22 +0000 (UTC)
Oct 21 13:15:23 mail postfix/cleanup[12076]: 181C8A00079: message-id=<EDD14E18-2B9C-4AC3-9D71-C771ADA2FF35@macgyver.com>
Oct 21 13:15:24 mail postfix/cleanup[12076]: warning: milter inet:mailu-rspamd:11332: can't read SMFIC_BODYEOB reply packet header: Application error
Oct 21 13:15:24 mail postfix/cleanup[12076]: 181C8A00079: milter-reject: END-OF-MESSAGE from unknown[000.000.000.000]: 4.7.1 Service unavailable - try again later; from=<mac@macgyver.com> to=<XXX@gmail.com> proto=ESMTP helo=<[127.0.0.1]>
Oct 21 13:15:24 mail postfix/smtpd[12073]: disconnect from unknown[000.000.000.000] ehlo=2 xclient=0/1 mail=1 rcpt=1 data=0/1 quit=1 commands=5/7
```

This `warning: milter inet:mailu-rspamd:11332: can't read SMFIC_BODYEOB reply packet header: Application error` is caused only when replying to a delivered email. Let's say I sent email from `macgyver.com` to `gmail.com` - that works. But when I try to reply from `gmail.com` to the delivered email, receiving `mail.macgyver.com` returns that error.

## rspamd log
rspamd pod logs seem to report rspamd crashing and respawning with:
```
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:23 #25(rspamd_proxy) <f425e8>; proxy; rspamd_message_parse: loaded message; id: <EDD14E18-2B9C-4AC3-9D71-C771ADA2FF35@macgyver.com>; queue-id: <181C8A00079>; size: 1315; checksum: <0fcf6ad88253e93b71ca6be142e36873>
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:23 #25(rspamd_proxy) rspamd_crash_sig_handler: caught fatal signal 7(Bus error), pid: 25, trace:
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:23 #25(rspamd_proxy) rspamd_crash_sig_handler: please see Rspamd FAQ to learn how to dump core files and how to fill a bug report
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:24 #1(main) <c2aa0a>; main; rspamd_check_termination_clause: rspamd_proxy process 25 terminated abnormally by signal: Bus error and created core file; please see Rspamd FAQ to learn how to extract data from core file and fill a bug report
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:24 #1(main) <c2aa0a>; main; rspamd_cld_handler: respawn process rspamd_proxy in lieu of terminated process with pid 25
```
Full log around that timestamp:
```
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:22 #25(rspamd_proxy) <438d31>; proxy; proxy_accept_socket: accepted milter connection from 10.42.0.61 port 52940
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:22 #25(rspamd_proxy) <438d31>; milter; rspamd_milter_process_command: got connection from 10.42.0.58:38946
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:22 #25(rspamd_proxy) <438d31>; proxy; proxy_milter_finish_handler: finished milter connection
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:22 #25(rspamd_proxy) <f425e8>; proxy; proxy_accept_socket: accepted milter connection from 10.42.0.61 port 52942
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:23 #25(rspamd_proxy) <f425e8>; milter; rspamd_milter_process_command: got connection from XXX.XXX.XXX.XXX:38946
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:23 #25(rspamd_proxy) <f425e8>; proxy; rspamd_message_parse: loaded message; id: <EDD14E18-2B9C-4AC3-9D71-C771ADA2FF35@macgyver.com>; queue-id: <181C8A00079>; size: 1315; checksum: <0fcf6ad88253e93b71ca6be142e36873>
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:23 #25(rspamd_proxy) rspamd_crash_sig_handler: caught fatal signal 7(Bus error), pid: 25, trace:
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:23 #25(rspamd_proxy) rspamd_crash_sig_handler: please see Rspamd FAQ to learn how to dump core files and how to fill a bug report
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:24 #1(main) <c2aa0a>; main; rspamd_check_termination_clause: rspamd_proxy process 25 terminated abnormally by signal: Bus error and created core file; please see Rspamd FAQ to learn how to extract data from core file and fill a bug report
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:24 #1(main) <c2aa0a>; main; rspamd_cld_handler: respawn process rspamd_proxy in lieu of terminated process with pid 25
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:26 #1(main) <c2aa0a>; main; rspamd_fork_worker: prepare to fork process rspamd_proxy (0); listen on: *
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:26 #26(rspamd_proxy) <c2aa0a>; main; rspamd_worker_set_limits: use system max file descriptors limit: 1024KiB cur and 1024KiB max
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:26 #26(rspamd_proxy) <c2aa0a>; main; rspamd_worker_set_limits: use system max core size limit: -1B cur and -1B max
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:26 #26(rspamd_proxy) <c2aa0a>; main; rspamd_handle_child_fork: starting rspamd_proxy process 26 (0); listen on: *:11332
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:26 #26(rspamd_proxy) <fet9mc>; cfg; rspamd_dns_resolv_conf_on_server: parsed nameserver 10.43.0.10 from resolv.conf
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:26 #26(rspamd_proxy) <fet9mc>; cfg; rspamd_dns_read_hosts_file: processed host file /etc/hosts; 9 records added
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <dyatkr>; map; rspamd_map_common_http_callback: need to reread cached map triggered by https://maps.rspamd.com/rspamd/spf_dkim_whitelist.inc.zst (0 our modify time, 1633982821 cached modify time)
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <dyatkr>; map; rspamd_map_read_cached: https://maps.rspamd.com/rspamd/spf_dkim_whitelist.inc.zst: read map data cached 1233 bytes compressed, 2871 uncompressed
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <dyatkr>; map; rspamd_map_file_read_callback: rereading map file /etc/rspamd/local.d/maps.d/spf_dkim_whitelist.inc.local
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <dyatkr>; map; read_map_file: /etc/rspamd/local.d/maps.d/spf_dkim_whitelist.inc.local: map file is not found; it will be read automatically if created
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <dyatkr>; map; rspamd_map_file_read_callback: rereading map file /var/lib/rspamd/spf_dkim_whitelist.inc.local
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <dyatkr>; map; read_map_file: /var/lib/rspamd/spf_dkim_whitelist.inc.local: map file is not found; it will be read automatically if created
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <dyatkr>; map; rspamd_kv_list_fin: read hash of 237 elements from https://maps.rspamd.com/rspamd/spf_dkim_whitelist.inc.zst
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <qamb1r>; map; rspamd_map_common_http_callback: need to reread cached map triggered by https://maps.rspamd.com/rspamd/dmarc_whitelist_new.inc.zst (0 our modify time, 1632206532 cached modify time)
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <qamb1r>; map; rspamd_map_read_cached: https://maps.rspamd.com/rspamd/dmarc_whitelist_new.inc.zst: read map data cached 4161 bytes compressed, 10807 uncompressed
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <qamb1r>; map; rspamd_map_file_read_callback: rereading map file /etc/rspamd/local.d/maps.d/dmarc_whitelist.inc.local
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <qamb1r>; map; read_map_file: /etc/rspamd/local.d/maps.d/dmarc_whitelist.inc.local: map file is not found; it will be read automatically if created
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <qamb1r>; map; rspamd_map_file_read_callback: rereading map file /var/lib/rspamd/dmarc_whitelist.inc.local
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <qamb1r>; map; read_map_file: /var/lib/rspamd/dmarc_whitelist.inc.local: map file is not found; it will be read automatically if created
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <qamb1r>; map; rspamd_kv_list_fin: read hash of 782 elements from https://maps.rspamd.com/rspamd/dmarc_whitelist_new.inc.zst
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <qbq3yk>; map; rspamd_map_common_http_callback: need to reread cached map triggered by https://maps.rspamd.com/rspamd/surbl-whitelist.inc.zst (0 our modify time, 1532778047 cached modify time)
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <qbq3yk>; map; rspamd_map_read_cached: https://maps.rspamd.com/rspamd/surbl-whitelist.inc.zst: read map data cached 4159 bytes compressed, 11647 uncompressed
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <qbq3yk>; map; rspamd_map_file_read_callback: rereading map file /etc/rspamd/local.d/maps.d/surbl-whitelist.inc.local
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <qbq3yk>; map; read_map_file: /etc/rspamd/local.d/maps.d/surbl-whitelist.inc.local: map file is not found; it will be read automatically if created
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <qbq3yk>; map; rspamd_map_file_read_callback: rereading map file /var/lib/rspamd/surbl-whitelist.inc.local
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <qbq3yk>; map; read_map_file: /var/lib/rspamd/surbl-whitelist.inc.local: map file is not found; it will be read automatically if created
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <qbq3yk>; map; rspamd_kv_list_fin: read hash of 828 elements from https://maps.rspamd.com/rspamd/surbl-whitelist.inc.zst
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <u9r7uu>; map; rspamd_map_common_http_callback: need to reread cached map triggered by https://maps.rspamd.com/rspamd/redirectors.inc.zst (0 our modify time, 1628688395 cached modify time)
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <u9r7uu>; map; rspamd_map_read_cached: https://maps.rspamd.com/rspamd/redirectors.inc.zst: read map data cached 4596 bytes compressed, 10348 uncompressed
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <u9r7uu>; map; rspamd_kv_list_fin: read hash of 1071 elements from https://maps.rspamd.com/rspamd/redirectors.inc.zst
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <k8f914>; map; rspamd_map_common_http_callback: need to reread cached map triggered by https://maps.rspamd.com/freemail/disposable.txt.zst (0 our modify time, 1561486969 cached modify time)
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <k8f914>; map; rspamd_map_read_cached: https://maps.rspamd.com/freemail/disposable.txt.zst: read map data cached 2359 bytes compressed, 5911 uncompressed
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <k8f914>; map; rspamd_kv_list_fin: read hash of 427 elements from https://maps.rspamd.com/freemail/disposable.txt.zst
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <fdp86m>; map; rspamd_map_common_http_callback: need to reread cached map triggered by https://maps.rspamd.com/freemail/free.txt.zst (0 our modify time, 1561287111 cached modify time)
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <fdp86m>; map; rspamd_map_read_cached: https://maps.rspamd.com/freemail/free.txt.zst: read map data cached 16999 bytes compressed, 56252 uncompressed
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <fdp86m>; map; rspamd_kv_list_fin: read hash of 4005 elements from https://maps.rspamd.com/freemail/free.txt.zst
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <o33omj>; map; rspamd_map_common_http_callback: need to reread cached map triggered by https://maps.rspamd.com/rspamd/mime_types.inc.zst (0 our modify time, 1616491407 cached modify time)
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <o33omj>; map; rspamd_map_read_cached: https://maps.rspamd.com/rspamd/mime_types.inc.zst: read map data cached 9599 bytes compressed, 48244 uncompressed
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <o33omj>; map; rspamd_map_file_read_callback: rereading map file /etc/rspamd/local.d/maps.d/mime_types.inc.local
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <o33omj>; map; read_map_file: /etc/rspamd/local.d/maps.d/mime_types.inc.local: map file is not found; it will be read automatically if created
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <o33omj>; map; rspamd_map_file_read_callback: rereading map file /var/lib/rspamd/mime_types.inc.local
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <o33omj>; map; read_map_file: /var/lib/rspamd/mime_types.inc.local: map file is not found; it will be read automatically if created
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <o33omj>; map; rspamd_kv_list_fin: read hash of 1540 elements from https://maps.rspamd.com/rspamd/mime_types.inc.zst
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <7n3qic>; map; rspamd_map_common_http_callback: need to reread cached map triggered by https://maps.rspamd.com/rspamd/mid.inc.zst (0 our modify time, 1626883711 cached modify time)
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <7n3qic>; map; rspamd_map_read_cached: https://maps.rspamd.com/rspamd/mid.inc.zst: read map data cached 465 bytes compressed, 762 uncompressed
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <7n3qic>; map; rspamd_map_file_read_callback: rereading map file /etc/rspamd/local.d/maps.d/mid.inc
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <7n3qic>; map; read_map_file: /etc/rspamd/local.d/maps.d/mid.inc: map file is not found; it will be read automatically if created
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <7n3qic>; map; rspamd_map_file_read_callback: rereading map file /etc/rspamd/local.d/mid.inc
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <7n3qic>; map; read_map_file: /etc/rspamd/local.d/mid.inc: map file is not found; it will be read automatically if created
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <7n3qic>; map; rspamd_kv_list_fin: read hash of 30 elements from https://maps.rspamd.com/rspamd/mid.inc.zst
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <fet9mc>; lua; lua_redis.lua:1207: uploaded redis script to 10.43.206.241:6379 with id 1, sha: b2b5aaa894dc3056e6ac294e44adbd0a1ca702b6
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <fet9mc>; lua; lua_redis.lua:1207: uploaded redis script to 10.43.206.241:6379 with id 5, sha: 3356099ff58c7e8893283c259278305d0d813a84
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <fet9mc>; lua; lua_redis.lua:1207: uploaded redis script to 10.43.206.241:6379 with id 6, sha: da3a534c5a16cf973cfab2ba50c1fb8461a87093
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <fet9mc>; lua; lua_redis.lua:1207: uploaded redis script to 10.43.206.241:6379 with id 2, sha: a43800941e2820ed8d764d50dfd9c142beddde68
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <fet9mc>; lua; lua_redis.lua:1207: uploaded redis script to 10.43.206.241:6379 with id 3, sha: 3b7b7539e4555fa579ead520dcc3a85d8a25ceab
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <fet9mc>; lua; lua_redis.lua:1207: uploaded redis script to 10.43.206.241:6379 with id 4, sha: b7bc61549b632aa0a12b5efd54e8b775e6d7f048
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <151c30>; proxy; proxy_accept_socket: accepted milter connection from 10.42.0.61 port 52984
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <151c30>; milter; rspamd_milter_process_command: got connection from [::1]:39825
mailu-rspamd-548cbc984b-9g6tm rspamd 2021-10-21 13:15:27 #26(rspamd_proxy) <151c30>; proxy; proxy_milter_finish_handler: finished milter connection
```

Things to note:
- domains uses DNSSEC by Cloudflare, traffic to mail.macgyver.com is not proxified by Cloudflare
- all relevant ports on the router's firewall are routed to the K3s master node, mail delivery works only with postfix's `nodeSelector` set to master, but I will open a separate ticket for that
- mxtoolbox.com does not report any errors
- reverse PTR is set for the mail domain
- certificate from Letsencrypt is valid 

@ping https://github.com/Mailu/Mailu/issues/1200

## Questions
Which image are we supposed to be using with RPi? Various people seem to have various degree of success but there is no clear directive which image to use. Other pods run fine on RPi using leolivier's mailu images - it is just rspamd causing trouble in my case.
