### ISSUE TITLE
[BUG] rspamd and clamav goes in pending state due to affinity rules

### ISSUE THREAD

**Issue by adrihanu** [Mailu/helm-charts#155]
**Describe the bug**

When running with default values for `rspamd` and `clamav` they both go in pending state due to affinity rules. For both of those pods I see the same message: `1 node(s) didn't match pod affinity rules`.

It seems like affinity rules in [`values.yaml`](https://github.com/Mailu/helm-charts/blob/b9e147c48dfe3a76632c1d62285120755bdffb51/mailu/values.yaml) are specified for both [`rspamd`](https://github.com/Mailu/helm-charts/blob/b9e147c48dfe3a76632c1d62285120755bdffb51/mailu/values.yaml#L370) and [`clamav`](https://github.com/Mailu/helm-charts/blob/b9e147c48dfe3a76632c1d62285120755bdffb51/mailu/values.yaml#L407) so they can't start, as they are dependent on each other. Maybe it's enough to just specify affinity rules just for `clamav` and make sure it runs on the same node as `rspamd`? This would probably also solve the problems described in https://github.com/Mailu/helm-charts/issues/129.

**Environment**

`Mailu 1.9` with `helm chart 0.3.0`

Running on `Ubuntu 20.04.3` with `Microk8s v1.23.3`

**Additional context**

<details><summary>describe mailu-clamav</summary>

```yaml

Name:           mailu-clamav-6479d79b84-48878

Namespace:      mailu-mailserver

Priority:       0

Node:           

Labels:         app=mailu

                component=clamav

                pod-template-hash=6479d79b84

Annotations:    

Status:         Pending

IP:             

IPs:            

Controlled By:  ReplicaSet/mailu-clamav-6479d79b84

Containers:

  clamav:

    Image:      mailu/clamav:1.9.10

    Port:       3310/TCP

    Host Port:  0/TCP

    Limits:

      cpu:     1

      memory:  2Gi

    Requests:

      cpu:      1

      memory:   1Gi

    Liveness:   exec [/health.sh] delay=0s timeout=5s period=10s #success=1 #failure=3

    Readiness:  exec [/health.sh] delay=0s timeout=5s period=10s #success=1 #failure=1

    Startup:    exec [/health.sh] delay=0s timeout=5s period=10s #success=1 #failure=60

    Environment:

      LOG_LEVEL:  DEBUG

    Mounts:

      /data from data (rw,path="clamav")

      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-6zk6b (ro)

Conditions:

  Type           Status

  PodScheduled   False 

Volumes:

  data:

    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)

    ClaimName:  mailu-storage

    ReadOnly:   false

  kube-api-access-6zk6b:

    Type:                    Projected (a volume that contains injected data from multiple sources)

    TokenExpirationSeconds:  3607

    ConfigMapName:           kube-root-ca.crt

    ConfigMapOptional:       

    DownwardAPI:             true

QoS Class:                   Burstable

Node-Selectors:              

Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s

                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s

Events:

  Type     Reason            Age                 From               Message

  ----     ------            ----                ----               -------

  Warning  FailedScheduling  3m35s               default-scheduler  0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.

  Warning  FailedScheduling  3m24s               default-scheduler  0/1 nodes are available: 1 node(s) didn't match pod affinity rules.

  Warning  FailedScheduling  26s (x1 over 116s)  default-scheduler  0/1 nodes are available: 1 node(s) didn't match pod affinity rules.

```
</details>

<details><summary>describe mailu-rspamd</summary>

```yaml

Name:           mailu-rspamd-57b976987-8dfck

Namespace:      mailu-mailserver

Priority:       0

Node:           

Labels:         app=mailu

                component=rspamd

                pod-template-hash=57b976987

Annotations:    

Status:         Pending

IP:             

IPs:            

Controlled By:  ReplicaSet/mailu-rspamd-57b976987

Containers:

  rspamd:

    Image:       mailu/rspamd:1.9.10

    Ports:       11332/TCP, 11334/TCP

    Host Ports:  0/TCP, 0/TCP

    Limits:

      cpu:     600m

      memory:  600Mi

    Requests:

      cpu:      500m

      memory:   500Mi

    Liveness:   http-get http://:rspamd-http/ delay=0s timeout=5s period=10s #success=1 #failure=3

    Readiness:  http-get http://:rspamd-http/ delay=0s timeout=5s period=10s #success=1 #failure=1

    Startup:    http-get http://:rspamd-http/ delay=0s timeout=5s period=10s #success=1 #failure=90

    Environment:

      LOG_LEVEL:          DEBUG

      FRONT_ADDRESS:      mailu-front.mailu-mailserver.svc.cluster.local

      ADMIN_ADDRESS:      mailu-admin.mailu-mailserver.svc.cluster.local

      REDIS_ADDRESS:      mailu-redis.mailu-mailserver.svc.cluster.local

      ANTIVIRUS:          clamav

      ANTIVIRUS_ADDRESS:  mailu-clamav:3310

      SUBNET:             10.1.0.0/16

    Mounts:

      /etc/rspamd/local.d/maps.d from data (rw,path="rspamd-local.d-maps.d")

      /var/lib/rspamd from data (rw,path="rspamd")

      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-jf29p (ro)

Conditions:

  Type           Status

  PodScheduled   False 

Volumes:

  data:

    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)

    ClaimName:  mailu-storage

    ReadOnly:   false

  kube-api-access-jf29p:

    Type:                    Projected (a volume that contains injected data from multiple sources)

    TokenExpirationSeconds:  3607

    ConfigMapName:           kube-root-ca.crt

    ConfigMapOptional:       

    DownwardAPI:             true

QoS Class:                   Burstable

Node-Selectors:              

Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s

                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s

Events:

  Type     Reason            Age                 From               Message

  ----     ------            ----                ----               -------

  Warning  FailedScheduling  3m43s               default-scheduler  0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.

  Warning  FailedScheduling  3m32s               default-scheduler  0/1 nodes are available: 1 node(s) didn't match pod affinity rules.

  Warning  FailedScheduling  64s (x1 over 2m4s)  default-scheduler  0/1 nodes are available: 1 node(s) didn't match pod affinity rules.
```
</details>
