### ISSUE TITLE
[BUG] Duplicate entry for ENV value 'webdav' and 'webdav_address'

### ISSUE THREAD

**Issue by kooskaspers** [Mailu/helm-charts#165]
**Describe the bug**
When deploying the helm chart (1.3.1), I receive these two error:
```
spec.template.spec.containers[0].env[16].name: duplicate name "WEBDAV"
spec.template.spec.containers[0].env[18].name: duplicate name "WEBDAV_ADDRESS"
```

**Environment**
 - Kubernetes Platform [e.g. GKE, Rancher2, ...]
k3s (K8s Rev: v1.22.7+k3s1)
**Additional context**
helm chart 1.3.1
mailuVersion: 1.9.20

I've had a look into the objects created by the helm chart. Error seems valid, I'm seeing a duplicate ENV value for WEBDAV and WEBDAV_ADDRESS after running 
`helm upgrade --install mailu mailu/mailu -n mailserver --values values.yaml --version "0.3.1" --dry-run`
which gives a look into the objects created:
```

    spec:
      containers:
      - name: front
        image: mailu/nginx:1.9.20
        imagePullPolicy: Always
        volumeMounts:
          - name: certs
            mountPath: /certs
        env:
[..]
          - name: WEBDAV <----------------------------------------------
            value: none 
          - name: WEBDAV_ADDRESS <----------------------------------------------
            value: localhost 
          - name: ADMIN
            value: "true"
          - name: WEB_ADMIN
            value: "/admin"
          - name: WEBDAV <----------------------------------------------
            value: radicale 
          - name: WEBDAV_ADDRESS <----------------------------------------------
            value: mailu-webdav.mailserver.svc.cluster.local:5232
```
I did a double check of my values.yaml, but it doesn't seem to be a duplicate entry over there.
