### ISSUE TITLE
[BUG] Dovecot not showing Real IP correctly

### ISSUE THREAD

**Issue by itssoke** [Mailu/helm-charts#206]
**Describe the bug**
When accessing dovecot, Real IP is the frontend private IP, not the real client IP. 

```
Feb 14 20:25:54 imap-login: Info: Login: user=<xxxxx@example.com>, method=PLAIN, rip=10.0.3.7, lip=10.0.3.8, mpid=838, session=<xxxxxxxxxx>
```

With other dovecot settings and (maybe) service or ingress settings but not mailu (native dovecot) I get this:
```
Feb 14 20:25:54 imap-login: Info: Login: user=<xxxxx@example.com>, method=PLAIN, rip=80.58.61.229, lip=10.0.3.8, mpid=838, session=<xxxxxxxxxx>
```

If you see "rip" which is the real IP from the client is the correct public IP.

My values settings for front are:
```
hostPort:
    enabled: false

externalService:
    enabled: true
    type: LoadBalancer
    loadBalancerIP: 192.168.X.X
    externalTrafficPolicy: Local
```

**Environment**
 - Kubernetes in bare metal with metallb load balancer.
