### ISSUE TITLE
Admin uses wrong builtin redis service name

### ISSUE THREAD

**Issue by timoschwarzer** [Mailu/helm-charts#225]
**Describe the bug**
The `admin` component tries to use a wrong service name for the builtin `redis` instance. It tries to access Redis at `mail-mailu-redis-master.mail.svc.cluster.local:6379`, but the service is called `mail-redis-master` (note the missing `mailu`).

It then fails with `redis.exceptions.ConnectionError: Error -2 connecting to mail-mailu-redis-master.mail.svc.cluster.local:6379. Name does not resolve.`.

Creating a dummy service to alias the correct service fixes the issue.

**Environment**
K3s 1.26.3+k3s1
Mailu chart version 1.0.1
Namespace: mail

values.yaml:

```yaml
mailu:
  hostnames:
  - mail.example.com

  domain: example.com
  secretKey: redacted

  initialAccount:
    enabled: false

  welcomeMessage:
    enabled: false

  timezone: "Europe/Berlin"

  postgresql:
    enabled: true
    primary:
      persistence:
        enabled: true
        size: 512Mi
    auth:
      password: redacted

  redis:
    master:
      persistence:
        size: 256Mi

  global:
    database:
      roundcube:
        password: redacted

  persistence:
    single_pvc: false

  admin:
    persistence:
      size: 256Mi

  rspamd:
    persistence:
      size: 512Mi

  postfix:
    persistence:
      size: 512Mi

  dovecot:
    persistence:
      size: 20Gi
    resources:
      requests:
        cpu: 250m

  roundcube:
    persistence:
      size: 512Mi

  webmail:
    persistence:
      size: 512Mi

  front:
    nodeSelector:
      kubernetes.io/hostname: redacted
    hostPort:
      enabled: false
    externalService:
      enabled: false

  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-dns
```

**Comment by fastlorenzo** [comment]
Thanks for your report, I've tried to reproduce the issue but unfortunately wasn't able to.
Could you provide more detailed logs of the admin pod?
Could you also run the following in the admin pod and provide the output:

```bash
export  | grep redis
```

Thanks

**Comment by fastlorenzo** [comment]
@timoschwarzer checking again your values file, I notice everything is under the `mailu` key. Any reason for that? How do you deploy the chart?

**Comment by timoschwarzer** [comment]
@fastlorenzo oh that's probably a missing piece I completely forgot: I deployed the mailu chart as a dependency to be able to add custom resources to the chart:

Chart.yaml:

```yaml
apiVersion: v2
version: 1.0.0
name: mail
dependencies:
- name: mailu
  version: 1.0.1
  repository: https://mailu.github.io/helm-charts/
```
