### ISSUE TITLE
[BUG] Base64 encoded RELAYUSER and RELAYPASSWORD are not decoded

### ISSUE THREAD

**Issue by Grennith** [Mailu/helm-charts#236]
**Describe the bug**
The RELAYUSER and RELAYPASSWORD set are encoded to base64 format and quoted:
```
  {{ .Values.externalRelay.usernameKey -}}: {{ (include "mailu.externalRelay.username" . ) | toString | b64enc | quote }}
  {{ .Values.externalRelay.passwordKey -}}: {{ (include "mailu.externalRelay.password" . ) | toString | b64enc | quote }}
```
https://github.com/Mailu/helm-charts/blob/master/mailu/templates/secret-external-relay.yaml#L17

Now these values are passed through to the postfix pod (including quotes!):
```
{{- if and .Values.externalRelay.host (not .Values.externalRelay.existingSecret) }}
- name: RELAYUSER
  valueFrom:
    secretKeyRef:
      name: {{ include "mailu.externalRelay.secretName" . }}
      key: {{ .Values.externalRelay.usernameKey }}
- name: RELAYPASSWORD
  valueFrom:
    secretKeyRef:
      name: {{ include "mailu.externalRelay.secretName" . }}
      key: {{ .Values.externalRelay.passwordKey }}
{{- end }}
```
https://github.com/Mailu/helm-charts/blob/master/mailu/templates/_secrets.tpl#L78

The values of RELAYUSER and RELAYPASSWORD are _never_ decoded however and passed through to sasl_passwd in Mailu:
`{{ RELAYHOST }} {{ RELAYUSER }}:{{ RELAYPASSWORD }}`
https://github.com/Mailu/Mailu/blob/master/core/postfix/conf/sasl_passwd#L1

The sasl_passwd file in turn is transformed into lmdb format. During TLS auth, the username and password are then base64 encoded automatically resulting in the original username and password being encoded twice basically resulting in the wrong password read by the remote server.

**Environment**
 - Kubernetes Platform [e.g. GKE, Rancher2, ...]

**Additional context**
Manually creating a secret (using existing secret) or editing the values in the autogenerated secret to hold the values in a non-encoded format has postfix run properly with relay working.

Using an existing secret results in the pod not passing RELAYUSER and RELAYPASSWORD at all:
`{{- if and .Values.externalRelay.host (not .Values.externalRelay.existingSecret) }}`
https://github.com/Mailu/helm-charts/blob/master/mailu/templates/_secrets.tpl#L77
