### ISSUE TITLE
[BUG] front pod error

### ISSUE THREAD

**Issue by Hokwang** [Mailu/helm-charts#249]
**Describe the bug**
Hi,

I want to install mailu. This is first time.

In my values.yaml
```
ingress:
  tls: false
```

and then, after install, there's error.
```
k -n mailu describe pod mailu-front-5dfd8d4bfb-ch6h8
...
Warning  FailedMount  55s (x9 over 3m3s)  kubelet            MountVolume.SetUp failed for volume "certs" : secret "mailu-certificates" not found
```

front pod alway have a volume
https://github.com/Mailu/helm-charts/blob/2a8eed8da871b1a2ec35675885e854e9fe6158c9/mailu/templates/front/deployment.yaml#L180-L188

But there's no secret.

**Environment**
 - AWS EKS

**Additional context**

**Comment by fastlorenzo** [comment]
Hi @Hokwang any reason why you don't want to use self-signed TLS? it's still better than no TLS at all

**Comment by chickenandpork** [comment]
Hi @Hokwang, it seems the deployment for mail does not switch out the TLS config.

Of course, the error is caused by the deployment looking for the secret to mount as a volume, even though you don't want to use TLS (which, as @fastlorenzo implies, is a concerning decision without understanding your reasons or constraints).

If you create a secret with empty values, allowing the deployment to mount a volume (that can be ignored), does your deployment complete ?

**Comment by outbackdingo** [comment]
the issue here, is the default is set to false in the chart, so it will always fail .. unless you manually change it to true, so i cant blame the guy if you turned it off by mistake.. i ran into the exact same issue and had to turn selfSigned: false to selfSigned: true... fix the chart.

**Comment by PPCM** [comment]
Hello,
I have the same issue. I can explain the raison: I use HAProxy in front for all my web applications, so I don't need HTTPS but HTTP connexion (HAProxy provides the HTTPS connexion)
@chickenandpork You said to create a secret with empty values, I did it, but how to pass the setup to values.yaml?

I tryed
```
ingress:
  annotations: {}
  apiVersion: ''
  enabled: true
  existingSecret: ''
  extraHosts: []
  extraPaths: []
  extraRules: []
  extraTls: []
  ingressClassName: ''
  path: /
  pathType: ImplementationSpecific
  proxyProtocol:
    imap: false
    imaps: false
    manageSieve: false
    pop3: false
    pop3s: false
    smtp: false
    smtps: false
    submission: false
  realIpFrom: ''
  realIpHeader: X-Forwarded-For
  secrets: [mailu-certificates]
  selfSigned: true
  tls: false
  tlsFlavorOverride: ''
```
With `mailu-certificates` the secret with empty values, but the installation fails

Thanks for your help
