### ISSUE TITLE
sso.php redirects to itself - 302 status

### ISSUE THREAD

**Issue by mwinters-stuff** [Mailu/helm-charts#260]
## Environment & Version

2.0.10, Installed via Helm Chart
Have existing 1.x install working fine.

### Environment

Kubernetes, Helm charts, Traefik proxy.

### Version

- Version: `2.0.10`

## Description

I have installed onto a fresh database, after a failed upgrade from 1.0.x.

When logging into the administration interface, that works perfectlly.

When attempting to login to WebMail, I get the error "Too Many Redirects", ERR_TOO_MANY_REDIRECTS.

Looking at the network debugging, "sso.php" is doing the redirects to itself.

**General**
```
Request URL: https://mail2.XXXX.XXX.nz/webmail2/sso.php
Request Method: GET
Status Code: 302 
Remote Address: 219.88.234.184:443
Referrer Policy: same-origin
```
**Response Headers**
```
cache-control: private, no-cache, no-store, must-revalidate, post-check=0, pre-check=0
content-length: 0
content-type: text/html; charset=UTF-8
date: Sat, 27 May 2023 05:30:03 GMT
expires: Sat, 27 May 2023 05:30:01 GMT
last-modified: Sat, 27 May 2023 05:30:01 GMT
location: sso.php
pragma: no-cache
referrer-policy: no-referrer
referrer-policy: same-origin
server: nginx
set-cookie: roundcube_sessauth=-del-; expires=Sat, 27-May-2023 05:29:01 GMT; Max-Age=0; path=/; HttpOnly; SameSite=Strict
strict-transport-security: max-age=31536000
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: sameorigin
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-permitted-cross-domain-policies: none
x-robots-tag: none
```
**Request Headers**
```
:authority: mail2.winters.org.nz
:method: GET
:path: /webmail2/sso.php
:scheme: https
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
accept-encoding: gzip, deflate, br
accept-language: en-NZ,en;q=0.9,en-GB;q=0.8,en-US;q=0.7
cookie: roundcube_sessid=HIDDEN; authelia_session=HIDDEN
session=HIDDEN
referer: https://mail2.XXXX.XXX.nz/admin/user/settings
sec-ch-ua: "Chromium";v="112", "Google Chrome";v="112", "Not:A-Brand";v="99"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Linux"
sec-fetch-dest: document
sec-fetch-mode: navigate
sec-fetch-site: same-origin
sec-fetch-user: ?1
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
```

## Replication Steps

The configuration is fairly default, with the usual hostnames and database configuration..

The traefik ingress route is:

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: mailu2
  namespace: default
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`mail2.XXXX.XXX.nz`) 
      kind: Rule
      services:
        - name: mailu-front
          namespace: mailu2
          port: 443
  tls:
    secretName: XXX-XX-nz-production-tls 

```

## Observed behaviour
Unable to get to the webmail interface.

## Expected behaviour
Expect to get to the webmail interface.

## Logs

Unable to find anything relevant in the logs.

**Comment by redimp** [comment]
Observing the very same behaviour. All I could find yet was in the `mailu-admin` log:

```
93.218.79.178 - - [29/May/2023:19:27:12 +0000] "GET /internal/auth/user HTTP/1.0" 200 0 "https://mailu.t3m4.net/sso/login?url=/webmail/" "Mozilla/5.0 (Macintosh;
10.0.2.216 - - [29/May/2023:19:27:12 +0000] "GET /internal/auth/email HTTP/1.0" 200 0 "-" "-"
93.218.79.178 - - [29/May/2023:19:27:13 +0000] "GET /internal/auth/user HTTP/1.0" 200 0 "https://mailu.t3m4.net/sso/login?url=/webmail/" "Mozilla/5.0 (Macintosh;
10.0.2.216 - - [29/May/2023:19:27:13 +0000] "GET /internal/auth/email HTTP/1.0" 200 0 "-" "-"
93.218.79.178 - - [29/May/2023:19:27:14 +0000] "GET /internal/auth/user HTTP/1.0" 200 0 "https://mailu.t3m4.net/sso/login?url=/webmail/" "Mozilla/5.0 (Macintosh;
10.0.2.216 - - [29/May/2023:19:27:14 +0000] "GET /internal/auth/email HTTP/1.0" 200 0 "-" "-"
93.218.79.178 - - [29/May/2023:19:27:15 +0000] "GET /internal/auth/user HTTP/1.0" 200 0 "https://mailu.t3m4.net/sso/login?url=/webmail/" "Mozilla/5.0 (Macintosh;
10.0.2.216 - - [29/May/2023:19:27:15 +0000] "GET /internal/auth/email HTTP/1.0" 200 0 "-" "-"
```

In the `mailu-front` log:
```
10.0.2.154 - - [29/May/2023:19:27:14 +0000] "GET /webmail/sso.php HTTP/1.1" 302 5 "https://mailu.xxx.net/sso/login?url=/webmail/" "Mozilla/5.0 (Macintosh; Intel
 Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
2023/05/29 19:27:14 [info] 11#11: *5832 client 10.0.0.15:48132 connected to 0.0.0.0:10143
2023/05/29 19:27:14 [error] 11#11: *5832 recv() failed (104: Connection reset by peer) while reading response from upstream, client: 10.0.0.15, server: 0.0.0.0:1
0143, login: "mailadmin@mailu.xxx.net", upstream: 10.43.124.49:143
10.0.2.154 - - [29/May/2023:19:27:15 +0000] "GET /webmail/sso.php HTTP/1.1" 302 5 "https://mailu.xxx.net/sso/login?url=/webmail/" "Mozilla/5.0 (Macintosh; Intel
 Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
2023/05/29 19:27:15 [info] 12#12: *5839 client 10.0.0.15:48148 connected to 0.0.0.0:10143
2023/05/29 19:27:15 [error] 12#12: *5839 recv() failed (104: Connection reset by peer) while reading response from upstream, client: 10.0.0.15, server: 0.0.0.0:1
0143, login: "mailadmin@mailu.xxx.net", upstream: 10.43.124.49:143
```

Same for `2.0.10` and `2.0.13`.

**Comment by mwinters-stuff** [comment]
@redimp Thanks, that resolved it - I had the `subnet` entry, as the default value but nothing worked until I removed the entry from the configuration.

Closing.

**Comment by tbscode** [comment]
Found this issue, helped me fix a related issue.

I was experiencing an infinite redirect when loading the web mailer ( also at `sso.php` ). After login I would see a `ERR_TOO_MANY_REDIRECTS` after a while.
But I was able to login to the admin dashboard.

I also had the `subnet: ` configured as default ``. I tried just setting `subnet: ""` hoping it would configure itself which It didn't ;).
Then I saw the [redme states that this has to be update](https://github.com/Mailu/helm-charts/blob/2eec0ca7de6a1f52dada011b2e80828e8e6ce602/mailu/README.md?plain=1#L965).

For me since I was using microk8s + calico I was able to find the pods subnet by looking for `CALICO_IPV4POOL_CIDR` in `microk8s kubectl describe daemonset calico-node -n kube-system`.

Now everything seems to work as expected with a minimal configuration like this.

```yaml
domain: $DOMAIN
hostnames:
  - $DOMAIN
initialAccount:
  enabled: true
  domain: $DOMAIN
  password: ...
  username: ...
logLevel: INFO
limits:
  authRatelimit:
    ip: 100/minute;3600/hour
    user: 100/day
  messageSizeLimitInMegabytes: 200
persistence:
  size: 100Gi
secretKey: ...
ingress:
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: $ISSUER_NAME
subnet: $SUBNET
```
