### ISSUE TITLE
Don't set `externalTrafficPolicy` when `externalService` is `ClusterIP`

### ISSUE THREAD

**Issue by baby-gnu** [Mailu/helm-charts#266]
**Describe the bug**

I can't deploy the helm with the following `values.yaml`:

```yaml
front:
  hostPort:
    enabled: false

  externalService:
    enabled: true
    type: ClusterIP
```

I get the following error:

```
Error: Service "mailu-front-ext" is invalid: spec.externalTrafficPolicy: Invalid value: "Local": may only be set when `type` is 'NodePort' or 'LoadBalancer'
```

**Environment**
 - Kubernetes Platform Scaleway

**Additional context**

I have an existing nginx ingress as `LoadBalancer` with correct TCP service forwarding.
