### ISSUE TITLE
Create a minimal best-practice values.yaml

### ISSUE THREAD

**Issue by NotANormalNerd** [Mailu/helm-charts#273]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to go through 2358 lines of default values files to find the 10 config options that are actually valuable for me that is running a default instance for personal use.

**Describe the solution you'd like**
Create a minimal values.yaml that I need for a default setup on a freshly setup default k8s cluster

here is my old 0.3.3 values.yaml (33 lines long and could probably be 5 shorter)
```yaml
certmanager:
  apiVersion: cert-manager.io/v1
  enabled: true
  issuerName: letsencrypt-production
  issuerType: ClusterIssuer
database:
  type: sqlite
domain: mailu.example
hostnames:
- mailservice.mailu.example
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
  className: ""
  externalIngress: true
  realIpFrom: 0.0.0.0/0
  realIpHeader: X-Forwarded-For
  tlsFlavor: cert
initialAccount:
  domain: mailu.example
  password: chang3m3!
  username: mailadmin
persistence:
  accessMode: ReadWriteOnce
  single_pvc: true
  size: 10Gi
postmaster: postmaster
roundcube:
  enabled: false
secretKey: somelongsecretkeyhere
```
