### ISSUE TITLE
Allow to set externalService labels

### ISSUE THREAD

**Issue by CRASH-Tech** [Mailu/helm-charts#275]
**Is your feature request related to a problem? Please describe.**
CIlium BGP CP selects LB class from service labels, not annotations and I can't set it

**Describe the solution you'd like**
```
externalService:
  enabled: true
   type: LoadBalancer
   labels: {}
```
