### ISSUE TITLE
[BUG] Bundled redis does not support arm64 without manual intervention

### ISSUE THREAD

**Issue by fiskhest** [Mailu/helm-charts#276]
**Describe the bug**
When configuring `redis.enabled=true`, statefulset reports a `exec format error`.

**Environment**
 - k3s

**Additional context**
I was able to overcome this by setting:
```
redis:
  ## @param redis.enabled Enable redis deployment through the redis subchart
  enabled: true

  volumePermissions:
    image:
      repository: bitnami/os-shell
      tag: 11-debian-11-r19
    enabled: true

  image:
    tag: 7.0.12-debian-11-r15
```
