### ISSUE TITLE
Document more NFS settings

### ISSUE THREAD

**Issue by fiskhest** [Mailu/helm-charts#277]
**Is your feature request related to a problem? Please describe.**
When migrating to the new helm chart, I had to find and set a whole load of settings for the installation to succeed

**Describe the solution you'd like**
A parameter key which will automatically template in these settings

**Describe alternatives you've considered**
Adding some comments to `values.yaml` which shows examples on how to enable this

**Additional context**
These are all settings I had to set to get things working in my environment. Anywhere a uid or gid is specified, it should match the NFS directory owner/group id

```
redis:
  enabled: true
  containerSecurityContext:
    enabled: true
    runAsGroup: 1000
    runAsUser: 1000

  securityContext:
    enabled: true
    fsGroup: 1000
    runAsUser: 1000

  volumePermissions:
    enabled: true

    ## @param redis.master.persistence.subPath Subpath in PVC; necessary if using single_pvc (set it to `/redis`)
    persistence:
      enabled: true
      size: 1Gi
      storageClass: "redis-pv"
      accessModes: [ReadWriteOnce]
      existingClaim: "redis-hdd"
      subPath: "redis"  # <--- I specifically got an error about using relative paths, so I had to remove the leading slash(!?)

dovecot:
  enabled: true

  securityContext:
    capabilities:
      add:
        - SYS_CHROOT
  overrides:
    dovecot.conf: |
      # More info here: https://mailu.io/1.8/kubernetes/mailu/index.html#dovecot  <-- this link is dead
      mail_nfs_index = yes
      mail_nfs_storage = yes
      mail_fsync = always
      mmap_disable = yes
      mail_max_userip_connections=100
      mail_uid = 1000
      mail_gid = 1000
```
