### ISSUE TITLE
[BUG] Credentials are being asked when upgrading van 1.2.0 to 1.4.0

### ISSUE THREAD

**Issue by kooskaspers** [Mailu/helm-charts#298]
**Describe the bug**
While upgrading to 1.4.0 i’m confronted with this error:

```
PASSWORDS ERROR: You must provide your current passwords when upgrading the release.
                 Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims.
                 Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases

    'global.database.roundcube.password' must not be empty, please add '--set global.database.roundcube.password=$ROUNDCUBE_DB_PASSWORD' to the command. To get the current value:

        export ROUNDCUBE_DB_PASSWORD=$(kubectl get secret --namespace "mailserver" mailu-roundcube -o jsonpath="{.data.roundcube-db-password}" | base64 -d)
```

Tried to get the secret via 
``` 
kubectl get secret --namespace "mailserver" mailu-roundcube -o jsonpath="{.data.roundcube-db-password}" | base64 -d 
```

But it looks like this secret is not available anymore :(. Is there any way to recover?

This is my values.yaml:

```
[...]                                                                                                                                                                    
  database:                                                                                                                                                                                              
    ## @param global.database.roundcube.database Name of the roundcube database                                                                                                                          
    ## @param global.database.roundcube.username Username to use for the roundcube database                                                                                                              
    ## @param global.database.roundcube.password Password to use for the roundcube database                                                                                                              
    ## @param global.database.roundcube.existingSecret Name of an existing secret to use for the roundcube database                                                                                      
    ## @param global.database.roundcube.existingSecretPasswordKey Name of the key in the existing secret to use for the roundcube database password                                                      
    roundcube:                                                                                                                                                                                           
      database: roundcube                                                                                                                                                                                
      username: roundcube                                                                                                                                                                                
      password: ""                                                                                                                                                                                       
      existingSecret: ""                                                                                                                                                                                 
      existingSecretPasswordKey: ""    
```

**Environment**

K3s version v1.25.6+k3s1 

**Additional context**
