### ISSUE TITLE
[BUG] Changes to immutable labels prevent migrations to newer chart versions

### ISSUE THREAD

**Issue by dgerhardt** [Mailu/helm-charts#318]
**Describe the bug**
The chart's template for the clamav StatefulSet currently sets common labels for `volumeClaimTemplates`. This is a problem because the labels are immutable and the template sets a value with the chart's version. As a consequence, updates to newer versions of the chart will fail.

**Environment**
 - Kubernetes 1.27
 - Helm 3.12
 - Mailu chart 1.5.0 (updating from 1.4.0)

**Additional context**
This seems to be a common pitfall for Helm charts: https://github.com/helm/charts/issues/7803

Manifest excerpt:
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    # This is fine:
    helm.sh/chart: mailu-1.4.0
  name: mailu-clamav
spec:
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      labels:
        # This causes problems during updates (immutable):
        helm.sh/chart: mailu-1.4.0
```
