### ISSUE TITLE
[BUG] global.storageClass is not applied to single_pvc

### ISSUE THREAD

**Issue by koeberlue** [Mailu/helm-charts#328]
**Describe the bug**
I set `global.storageClass` to `longhorn-crypto-global`. This worked for the following PVCs:

* `data-mailu-clamav-0`
* `redis-data-mailu-redis-master-0`

But when I looked at `mailu-storage`, it was assigned the default storage class (which is `longhorn` in my case).

**Environment**
 - RKE1 Single Node Cluster
 
**Values**

```
global:
  storageClass: longhorn-crypto-global
hostnames:
  - mail.<redacted>
domain: <redacted>
timezone: "Germany/Berlin"

ingress:
  enabled: true
  ingressClassName: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

front:
  hostPort:
    enabled: false
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 256Mi
admin:
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 256Mi
postfix:
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 256Mi
dovecot:
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 256Mi
rspamd:
  resources:
    requests:
      memory: 500Mi
      cpu: 600m
    limits:
      memory: 500Mi
clamav:
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 256Mi
webmail:
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 256Mi
oletools:
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 256Mi
```

**Additional context**
There seems to be no reference to `global.storageClass` in [`templates/pvc.yaml`](https://github.com/Mailu/helm-charts/blob/ee6b866e491f64a22f414a5f8c435e990912fb38/mailu/templates/pvc.yaml#L30)

**Workaround**

I set `persistence.storageClass` to `longhorn-crypto-global`. This seems to solve the issue, but I was expecting the `global` setting to be applied to _all_ PVCs.
