### ISSUE TITLE
mailu-front: using reloader on k8s

### ISSUE THREAD

**Issue by christf** [Mailu/helm-charts#330]
When using mailu on kubernetes via this helm chart, it is helpful to get cert-manager to renew certificates. This works even on split-horizon dns setups when configuring cert-manager to use external DNS. 

However due to the way to certificates are used, after renewal, the mailu-front pod requires a restart.
A common way of executing restarts of pods after secrets have changed is
https://github.com/stakater/Reloader

Using reloader hinges on the deployment having a specific annotation.
At the moment this mailu-chart does not provide the ability to annotate  just the deployment of the front containers.

It would be helpful to be able to annotate just the mailu-front deployments such that tools like reloader can ensure automatically renewed certificates are equally automatically used.

The current workaround is to use the commonAnnotations and annotate everything. This has the drawback of much increased scope for reloader. Hosting mail is complicated already and as such it would be best to limit the supporting tools poking at components of mailu as much as possible.

**Comment by christf** [comment]
https://drewdevault.com/2021/10/26/stalebot.html

**Comment by olebittner** [comment]
would also like this feature. I'm currently using a post-renderer to patch the annotation:
```yaml
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: mailu-front
            patch: |-
              - op: add
                path: /metadata/annotations/secret.reloader.stakater.com~1reload
                value:  mailu-certificates
```
