### ISSUE TITLE
Whenever I restart my kubernetes cluster running mailu my user accounts are lost.

### ISSUE THREAD

**Issue by lknite** [Mailu/helm-charts#331]
**Describe the bug**
Whenever I restart my kubernetes cluster running mailu my user accounts are lost.
Via the admin account I can then re-add the user accounts, and when the users log in the user's emails are there.

**Environment**
- kubernetes version v1.28.2 setup with kubeadm using redhat 9

**To reproduce**
- deploy using helm chart below
- login in as admin@domain account
- create a user@domain
- attempt to send an email so when you come back you can tell the data is still there
- drain all nodes of the cluster and reboot the k8s cluster nodes
- uncordon all nodes
- once mailu is back up try to login as user, you won't be able to as if account doesn't exist
- log in as admin & recreate the user account
- try again to login as user, you will be able to and the email you sent before will be there

**Additional context**
I've been using mailu over a year, and I love it, but this issue has always occurred.  I recently reinstalled everything cleanly to a new cluster a week ago, and after restarting the cluster for whatever reason noticed the issue is still occurring (and had to manually re-add my users).

I have all the PVCs as far as far as I know, what could be causing this issue?  How might I go about debugging it?

My helm chart has been updated as needed over time, perhaps I do need to specify so much, in any case, here it is:
```
mailu:

  postgresql:
    enabled: true

  hostnames:
  - mail.aarr.xyz

  domain: aarr.xyz

  # required for protecting authenticating cookies
  secretKey: <redacted>

  timezone: "Etc/UTC"

  # initial account to auto-create
  initialAccount:
    enabled: true
    username: administrator
    domain: aarr.xyz
    password: <redacted>

  persistence:
    single_pvc: false
    size: 100Gi
    accessMode: ReadWriteOnce

  # Pod cidr
  subnet: 172.16.0.0/12

  #
  limits:
    messageSizeLimitInMegabytes: 50
    authRatelimit:
      ip: 10/minute

  # Set ingress and loadbalancer config
  ingress:
    enabled: true
    ingressClassName: nginx
    tls: true
    annotations:
      cert-manager.io/issuer: cluster-letsencrypt-issuer
      cert-manager.io/issuer-kind: ClusterIssuer
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
    realIpHeader: X-Forwarded-For

  # Disable default open port setup which is more likely to result in an open relay
  front:
    hostPort:
      enabled: false

    # Required to avoid an open relay
    externalService:
      enabled: true
      type: LoadBalancer
      externalTrafficPolicy: Local

  admin:
    image:
      repository: ghcr.io/mailu/admin

  dovecot:
    image:
      repository: ghcr.io/mailu/dovecot
    resources:
      requests:
        memory: 500Mi
        cpu: 200m
      limits:
        memory: 500Mi
        cpu: 200m

  rspamd:
    image:
      repository: ghcr.io/mailu/rspamd
    startupProbe:
      timeoutSeconds: 3600 
    resources:
      requests:
        cpu: 200m
        #cpu: 600m
        memory: 500Mi
      limits:
        cpu: 200m
        #cpu: 600m
        memory: 500Mi

  clamav:
    image:
      repository: ghcr.io/mailu/clamav
    resources:
      limits:
        cpu: 200m
        #cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 200m
        #cpu: 1000m
        memory: 2Gi

  webmail:
    image:
      repository: ghcr.io/mailu/webmail

  webdav:
    image:
      repository: ghcr.io/mailu/webdav

  fetchmail:
    image:
      repository: ghcr.io/mailu/fetchmail

  postfix:
    image:
      repository: ghcr.io/mailu/postfix
    resources:
      limits:
        cpu: 400m
        #cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 400m
        #cpu: 1000m
        memory: 2Gi
```

**Comment by lknite** [comment]
I had enabled postgres but not the storage for the postgresdb, after adding this no more issue:
```
mailu:

  postgresql:
    enabled: true

    # this
    primary:
      persistence:
        enabled: true
```
