### ISSUE TITLE
[BUG] Dovecot Pod does not have valid certs for lmtp when front is provided with ExistingSecret

### ISSUE THREAD

**Issue by jamesarbrown** [Mailu/helm-charts#338]
Under 2.0.30 we are seeing this error on dovecot pod whilst debugging another issue

```
lmtp(1415): Error: SSL context initialization failed, disabling SSL: Can't load SSL certificate (ssl_cert setting): The certificate is empty 
Feb 19 20:52:10 lmtp(1415): Info: Connect from 10.42.1.56 
```

yet the certificate is fed into the ```ingress``` section of the helm chart as ExistingSecret, so it suggests that Dovecot is not getting provision to the same TLS certs as provided to the ```front```

To work around that we did this
```

  ## @param dovecot.extraVolumeMounts Optionally specify extra list of additional volumeMounts for the pod
  extraVolumeMounts:
      - name: certs
        mountPath: /certs

  ## @param dovecot.extraVolumes Optionally specify extra list of additional volumes for the pod(s)
  extraVolumes:
      - name: certs
        secret:
          defaultMode: 420
          items:
            - key: tls.crt
              path: cert.pem
            - key: tls.key
              path: key.pem
          secretName: example-uk-tls

  ## @param dovecot.overrides Enable dovecot overrides
  ## Example:
  ## overrides:
  ##   dovecot.conf: |
  ##     # More info here: https://mailu.io/1.8/kubernetes/mailu/index.html#dovecot
  ##     mail_nfs_index = yes
  ##     mail_nfs_storage = yes
  ##     mail_fsync = always
  ##     mmap_disable = yes
  ##     mail_max_userip_connections=100
  ##'overrides: {}
  overrides:
    dovecot.conf: |
      ssl_cert = </certs/cert.pem
      ssl_key = </certs/key.pem
```

And as far as we can tell the log error is now quiet
