### ISSUE TITLE
[BUG] Non-working parameters parameters in values.yaml "nodeSelector" and "affinity"

### ISSUE THREAD

**Issue by gomin1d** [Mailu/helm-charts#341]
**Describe the bug**
This file https://github.com/Mailu/helm-charts/blob/master/mailu/values.yaml has the following parameters:  
```
## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
## @param tolerations Tolerations for pod assignment
tolerations: []

## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
## @param affinity Affinity for pod assignment
affinity: {}
  ```

But these parameters do not work.

**Environment**
Self-hosted kubespray, argocd, mailu helm:
```
repoURL: https://mailu.github.io/helm-charts/
targetRevision: 1.5.0
chart: mailu
```

**Comment by gomin1d** [comment]
up

**Comment by hans-fischer** [comment]
Is the maintainer still alive?

**Comment by gomin1d** [comment]
> Is the maintainer still alive?

yes, but I'm ready to write "up" until I die

**Comment by hans-fischer** [comment]
> > Is the maintainer still alive?
> 
> yes, but I'm ready to write "up" until I die

You are not a maintainer of this helm-repo, right?

**Comment by gomin1d** [comment]
> > > Is the maintainer still alive?
> > 
> > 
> > yes, but I'm ready to write "up" until I die
> 
> You are not a maintainer of this helm-repo, right?

No. But I can share my solution. I don't know how good it is.

Tree files:
applications/mailu.yaml
mailu-helm/deployment-patch.yaml
mailu-helm/kustomization.yaml
mailu-helm/values.yaml

`applications/mailu.yaml`
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mailu
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: git@gitlab.com:***secret***/***secret***.git
      path: 'mailu-helm'
      targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gomin1ds
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

`mailu-helm/kustomization.yaml`
```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gomin1ds

helmCharts:
  - name: mailu
    releaseName: mailu
    version: 1.5.0
    repo: https://mailu.github.io/helm-charts/
    namespace: gomin1ds
    valuesFile: values.yaml

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
```

`mailu-helm/deployment-patch.yaml`
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: not_important
spec:
  template:
    spec:
      nodeSelector:
        'kubernetes.io/hostname': '***secret***'
      tolerations:
        - key: "host"
          operator: "Equal"
          value: "critical"
          effect: "NoSchedule"
```

`mailu-helm/values.yaml`
```
oletools:
  enabled: false
subnet: 10.233.64.0/18
front:
  hostPort:
    enabled: false
domain: ***secret***
hostnames:
  - ***secret***
timezone: Europe/Kyiv
ingress:
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
webmail:
  enabled: false
logLevel: INFO
limits:
  authRatelimit:
    ip: 100/minute;3600/hour
    user: 100/day
  messageSizeLimitInMegabytes: 200
persistence:
  hostPath: /var/lib/kubernetes-mailu
clamav:
  enabled: false
redis:
  volumePermissions:
    enabled: true
  master:
    nodeSelector:
      'kubernetes.io/hostname': '***secret***'
    tolerations:
      - key: "host"
        operator: "Equal"
        value: "critical"
        effect: "NoSchedule"
    persistence:
      existingClaim: mailu-redis-pvc
initialAccount:
  enabled: true
  domain: ***secret***
  password: mailadmin
  username: mailadmin
  mode: "update"
```
