### ISSUE TITLE
[BUG] After upgrading to 2.0.0 get 301 redirect loop from front

### ISSUE THREAD

**Issue by mglants** [Mailu/helm-charts#352]
**Describe the bug**
when accessing web interface, got redirected loop

**Environment**
 - Talos Kubernetes
 -  Ingress nginx
 - Mailu 2024.06.3

**Additional context**

Imap works normally 
```
92.168.51.254 - - [25/Jun/2024:03:51:32 +0300] "GET / HTTP/1.1" 301 162 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
192.168.51.254 - - [25/Jun/2024:03:51:32 +0300] "GET / HTTP/1.1" 301 162 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
192.168.51.254 - - [25/Jun/2024:03:51:32 +0300] "GET / HTTP/1.1" 301 162 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
```
Values.yaml
```
    hostnames:
      - mail.ur30.ru
      - webmail.ur30.ru

ingress:
      ## @param ingress.enabled Enable external ingress
      enabled: true
      ingressClassName: nginx

      annotations:
        external-dns.alpha.kubernetes.io/target: ingress.ur30.ru
        cert-manager.io/cluster-issuer: letsencrypt-prod
      tls: true

      ## @param ingress.realIpHeader SrealIpFromets the value of `REAL_IP_HEADER` environment variable in the `front` pod
      realIpHeader: X-Forwarded-For

      ## @param ingress.realIpFrom Sets the value of `REAL_IP_FROM` environment variable in the `front` pod
      realIpFrom: 10.244.0.0/16,10.96.0.0/12
```
