### ISSUE TITLE
[BUG] incorrect SSL handling for kubernetes on frontend container behind reverse proxy

### ISSUE THREAD

**Issue by prutseltje** [Mailu/helm-charts#357]
**Describe the bug**
Default ingress TLS settings in kubernetes results in a 301 redirect loop

**Environment**
 - K3S

**Additional context**
TLS_FLAVOR is set to cert on kubernetes, causing the nginx container to listen on port 443, instead of port 80
Setting ```ingress.tlsFlavorOverride=mail``` seems to resolve it.

From my values.yml:
```yml
front:
    externalService:
        enabled: true
        externalTrafficPolicy: Local
        loadBalancerIP: 1.2.3.4
        type: LoadBalancer
    hostPort:
        enabled: false
hostnames:
    - mail.mydomain.com
    - imap.mydomain.com
ingress:
    annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/proxy-body-size: 52m
    enabled: true
    ingressClassName: nginx
    realIpFrom: 10.0.0.0/16
    tlsFlavorOverride: mail
```
