### ISSUE TITLE
[BUG] 302 Redirect on first proxy-auth login

### ISSUE THREAD

**Issue by mglants** [Mailu/helm-charts#361]
**Describe the bug**
302 Redirect on first proxy-auth login
After page refresh everything works just fine

**Environment**
 - Kubernetes talos linux

**Additional context**
Ingress annotations
```
        nginx.ingress.kubernetes.io/auth-response-headers: Set-Cookie,X-mailu-email
        nginx.ingress.kubernetes.io/auth-signin: /outpost.goauthentik.io/start?rd=$escaped_request_uri
        nginx.ingress.kubernetes.io/auth-snippet: proxy_set_header X-Forwarded-Host $http_host;
        nginx.ingress.kubernetes.io/auth-url: http://ak-outpost-authentik-embedded-outpost.infra.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
```
CIDR settings
```
proxyAuth.whitelist: 10.244.0.0/16,10.96.0.0/12
ingress.realIpFrom: 10.244.0.0/16,10.96.0.0/12
subnet: 10.244.0.0/16
```
Proxy auth settings
```
    proxyAuth:
      ## @param proxyAuth.whitelist Comma separated list of CIDRs of proxies to trust for authentication
      whitelist: 10.244.0.0/16,10.96.0.0/12

      ## @param proxyAuth.header HTTP header containing the email address of the user to authenticate
      header: X-mailu-email

      ## @param proxyAuth.create Whether non-existing accounts should be auto-created
      create: 'false'
```
<img width="926" alt="image" src="https://github.com/user-attachments/assets/8d50c8ba-7573-4e12-ae44-c76052b1f98a">
