### ISSUE TITLE
help with mailu on k8s

### ISSUE THREAD

**Issue by melbruki** [Mailu/helm-charts#391]
I tried all the various tlsFlavorOverride options, but the problem seems to be that it uses http01. Since the pod needs a certificate to start and cannot complete the challenge without coming up first, this creates a chicken-and-egg problem where the certificate request fails.

When I enable the ingress and external service, I can get a certificate on the ingress for the webmail and admin interfaces, but not for the mail ports.

I’m running a bare-metal, multi-node Kubernetes cluster with a load balancer. The following is the configuration I’ve tried:

```

externalService:
  enabled: true
  type: LoadBalancer

# Set external ingress config
ingress:
  enabled: true

tlsFlavorOverride: "letsencrypt"

  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"


```

in the end, I created a certificate resource using dns01 clusterissuer and obtained a certificate named mailu-certificates. Then, I disabled the ingress and external service. I modified the template so the front service type is set to LoadBalancer, with the external traffic policy set to Local. Everything seemed to work—at least initially.

However, when I accessed /admin/domain/details, I encountered an error. After checking the logs, I found the following traceback:

```
  File "/app/mailu/models.py", line 260, in dns_autoconfig
    ports = {int(port.strip()) for port in app.config['PORTS'].split(',')}.union({465, 993})
ValueError: invalid literal for int() with base 10: ''
```
This suggests something is either wrong with the Helm chart or my values.yaml file configuration. Could anyone help diagnose what might be causing this issue?
