### ISSUE TITLE
K8s cant access webmail to many redirection's

### ISSUE THREAD

**Issue by fr3sh** [Mailu/helm-charts#401]
I have a basic instalation of mailu on k8s. I cant get to work the webmail site. I try to acces but got to many redirections  and I don't know why its happend. 

Basic values.yaml

![Image](https://github.com/user-attachments/assets/f1259bfe-1dee-414a-ac35-62fd0dd77264)

Instalation made by helm 
sudo helm install mailu mailu/mailu -f values.yaml -n mailu

When I try to access webmail

![Image](https://github.com/user-attachments/assets/a87a48f2-fb5e-4803-898d-dc5bcc0075ac)

logs on front when i try to access webmail

![Image](https://github.com/user-attachments/assets/ed735ce1-f486-4d3c-96f5-1cc8f84a4c17)

Front admin panel is working correctly:

![Image](https://github.com/user-attachments/assets/9bbdf082-20a3-42b9-8935-03b1be9033f0)

this is the only logs on webmail:

![Image](https://github.com/user-attachments/assets/94428743-1af1-4760-8ea3-6d4e420daa31)

what Im missing?  Please help me

**Comment by fr3sh** [comment]
> I've also noticed that you've set several helm values that do not exist.
> 
> What did you use as reference when you've written your `values.yaml`?
> 
> * `webmail.forceHttps` is for instance non existing
> * `ingress.tls` is actually a boolean value
> * `tls.certManager` does also not exist
> * ...
> 
> Please have another look at the [Chart README](https://github.com/Mailu/helm-charts/blob/master/mailu/README.md) and check your configuration. There are also great Comments in the [default `values.yaml`](https://github.com/Mailu/helm-charts/blob/master/mailu/values.yaml) file that explains almost any value of the helm chart in detail

Yes. That was my "trials and errors".

**Comment by fr3sh** [comment]
> What is the PodCIDR of your Cluster?
> 
> The `subnet` value of the chart must be set to that value. (see [Chart README](https://artifacthub.io/packages/helm/mailu/mailu#all-services-are-running-but-authentication-fails-for-webmail-and-imap))

Thats is interesting. I will try to set it up. My cluster use calico. My settings for the claster are:

![Image](https://github.com/user-attachments/assets/07b0e6bd-12e4-42ab-9b94-5d964f274fa5)

![Image](https://github.com/user-attachments/assets/901efe5b-fe0b-4960-bf26-77a8d8d74a9c)

![Image](https://github.com/user-attachments/assets/9889c66e-d301-43e9-b1a6-b1c1e947b5e6)

**Comment by fr3sh** [comment]
@aki-ks  that was it. THANK YOU!!!!

**Comment by centayne-ctrl** [comment]
@fr3sh / @aki-ks - having a similar issue (at least in its symptoms constant redirect until receiving a too many redirects message) - but I am missing something. 

I've configured my subnet parameter to match my CIDR for my kubernetes env- but looks like the proxy auth is being forwarded to IMAP / dovecot then rejected - but I can't figure out why dovecot is rejecting it - 

``` sh

# kubectl describe ippool default
Name:         default-ipv4-ippool
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  projectcalico.org/v3
Kind:         IPPool
Metadata:
  Creation Timestamp:  2023-12-12T01:29:28Z
  Resource Version:    1168
  UID:                 6041d408-a2e2-4d0c-89b2-80f255a7c633
Spec:
  Allowed Uses:
    Workload
    Tunnel
  Block Size:     26
  Cidr:           172.16.0.0/16
  Ipip Mode:      Always
  Nat Outgoing:   true
  Node Selector:  all()
  Vxlan Mode:     Never
Events:           <none>
```



Log from Mailu-Front
``` logs
Aug 22 10:13:33 imap-login: Info: proxy(admin@example.com,10.103.255.109:143): Login failed: [AUTHENTICATIONFAILED] Authentication failed.: user=<admin@example.com>, method=PLAIN, rip=172.16.34.194, rport=48802, lip=172.16.34.239, lport=10143, TLS
Aug 22 10:13:33 imap-login: Info: Disconnected: Connection closed (proxy dest auth failed): user=<admin@example.com>, method=PLAIN, rip=172.16.34.194, rport=48802, lip=172.16.34.239, lport=10143, TLS
```

Log from IMAP / DOVECOT
``` logs
Aug 22 10:13:03 imap-login: Info: Disconnected: Connection closed (auth failed, 1 attempts in 2 secs): user=<admin@example.com>, method=PLAIN, rip=172.16.34.194, lip=172.16.34.239, secured, session=<goVsc/E8mNmsECLC>
```

``` yaml
# custom-values.yaml for Mailu with PostgreSQL and single PVC
domain: example.com
hostnames:
  - mail.example.com
  
subnet: "172.16.0.0/16" # aka my pod-cidr

logLevel: "DEBUG"

initialAccount:
  username: admin
  password: **** # Replace with a secure password
  domain: example.com

persistence:
  single_pvc: true
  enabled: true
  storageClass: "nfs-client"
  accessMode: ReadWriteOnce
  size: 50Gi

ingress:
  enabled: true
  annotations:
      metallb.io/allow-shared-ip: "true"
  realIpHeader: X-Forwarded-For
  realIpFrom: "172.16.0.0/16"

proxyAuth:
  whitelist: "172.16.0.0/16"
  header: "X-Auth-Email"
  create: true

front:
  enabled: true
  hostPort:
    enabled: true
  externalService:
    enabled: true
    type: LoadBalancer
    ## Example for LoadBalancer:
    ## type: LoadBalancer
    loadBalancerIP: 192.168.193.66
    externalTrafficPolicy: "Local"
    annotations:
      metallb.io/allow-shared-ip: "true"
    ports:
      pop3: false
      pop3s: true
      imap: false
      imaps: true
      smtp: true
      smtps: true
      submission: false
      manageSieve: true
    nodePorts:
      pop3: 110
      pop3s: 995
      imap: 143
      imaps: 993
      smtp: 25
      smtps: 465
      submission: 587
      manageSieve: 4190


admin:
  enabled: true
redis: 
  enabled: true
  persistence:
    enabled: true
    storageClass: "nfs-client"
    size: 8Gi

postfix:  
  resources:
    ## Example:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 2Gi

dovecot:
  enabled: true
  resources:
    
      ## limits:
      ##    cpu: 500m
      ##    memory: 500Mi
      limits:
        cpu: 500m
        memory: 500Mi
      ## Examples:
      ## requests:
      ##    cpu: 25m
      ##    memory: 25Mi
      requests:
        cpu: 25m
        memory: 25Mi
rspamd:
  enabled: true
  persistence: 
    enabled: true
    size: 8Gi
    storageClass: "nfs-client"
  resources:  
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 1
      memory: 1Gi

##antispam:
##  enabled: true
##antivirus:
##  enabled: true

clamav:
  enabled: true
  persistence:
    enabled: true
    size: 2Gi
    storageClass: "nfs-client"
  resources:
    requests:
      memory: "1Gi"
      cpu: 1
    limits:
      memory: "4Gi"
      cpu: 4

# Optional: enabling web admin UI and webmail

webmail:
  enabled: true

tika:
  enabled: true
# Optional: override image repo and tags if needed
image:
  repository: mailu/mailu
  tag: latest

podSecurityContext:
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001
  fsGroupChangePolicy: "OnRootMismatch"


```
