### ISSUE TITLE
[BUG] Your DNS resolver at 172.20.0.10 isn't doing DNSSEC validation

### ISSUE THREAD

**Issue by greenhua** [Mailu/helm-charts#402]
**MailU is not starting on EKS**
MailU mailu-admin is not starting with error message 

"CRITICAL:root:Your DNS resolver at 172.20.0.10 isn't doing DNSSEC validation; Please see https://mailu.io/master/faq.html#the-admin-container-won-t-start-and-its-log-says-critical-your-dns-resolver-isn-t-doing-dnssec-validation."

**Expected behavior**
Running MailU

**Environment:**

- **Helm Chart Version**: 2.1.2
- **Helm Version**: v3.16.4
- **Kubernetes Version**: 1.32
- **Kubernetes Platform**: EKS
- **Mailu Version**: 2.1.2
- **appVersion**: 2024.06.10
- **CoreDNS**: v1.11.4-eksbuild.2

**Values.yaml Configuration**
```
domain: maindomain.com

hostnames:
  - mail.maindomain.com

initialAccount:
  username: admin
  domain: maindomain.com
  password: SuperSecret123


ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  tls:
    - hosts:
        - mail.maindomain.com
      secretName: mailu-tls
  hosts:
    - host: mail.maindomain.com
      paths:
        - path: /
          pathType: Prefix
```
**helm show chart mailu/mailu**
```
apiVersion: v2
appVersion: 2024.06.10
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 2.8.0
- condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 17.15.*
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 11.9.*
- condition: mariadb.enabled
  name: mariadb
  repository: https://charts.bitnami.com/bitnami
  version: 12.2.*
description: This chart installs the Mailu mail system on kubernetes
home: https://mailu.io
icon: https://mailu.io/master/_images/logo.png
keywords:
- mailu
- mail
- email
- smtp
- imap
- pop3
- webmail
- postfix
- dovecot
- roundcube
maintainers:
- name: Mailu
  url: https://mailu.io
name: mailu
sources:
- https://github.com/Mailu/helm-charts/
version: 2.1.2
```
