### ISSUE TITLE
[BUG] mysql database schema and user for MailU don´t be created at startup

### ISSUE THREAD

**Issue by tgruenert** [Mailu/helm-charts#55]
**Describtion**
At first startup no user or database for MailU would be created. So startup without existing database is not working.

**Environment**
 - Kubernetes 1.16.3 with Rancher
 
values.yaml like this:
```
database:
  type: mysql
  roundcubeType: mysql
  mysql:
    rootPassword: my-secret-secret
    database: mailu
    user: mailu
    password: my-secret-secret
    roundcubeDatabase: roundcube
    roundcubeUser: roundcube
    roundcubePassword: my-secret-secret
```

**Additional context**
For Roundcube i can see database user and schema.
